plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.maven.publish)
}

android {
    namespace "me.hgj.mvvmhelper"

    compileSdkVersion  36
    defaultConfig {
        minSdk  23
        targetSdk  36
        versionCode 22
        versionName "1.2.1"

        consumerProguardFiles "consumer-rules.pro"
    }

    buildFeatures {
        viewBinding = true
        dataBinding = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    kotlin {
        jvmToolchain(17) // 自动设置 Java 17 兼容性
    }
    publishing {
        singleVariant("release")
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.hegaojian'
                artifactId = 'MvvmHelper'
                version = '1.2.2'
            }
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.constraintlayout)
    //adapter （有些人不想用，或者想使用更高版本的，这里不使用api的方式集成）
    implementation libs.baserecyclerviewadapterhelper

    // 协程基础库
    api libs.kotlinx.coroutines.core
    api libs.kotlinx.coroutines.android
    //lifecycle
    api libs.androidx.lifecycle.runtime.ktx
    // viewModel
    api libs.androidx.lifecycle.viewmodel.ktx
    // liveData
    api libs.androidx.lifecycle.livedata.ktx

    //Toast
    api libs.toaster
    //log
    api libs.log
    api libs.gson
    api libs.dialog
    api libs.immersionbar

    //启动优化异步加载
    api libs.anchors
    //http
    implementation libs.okhttp
    api libs.rxhttp
    //refresh刷新
    api libs.refresh.layout.kernel
    api libs.refresh.header.classics
    //利用liveData发送全局消息
    api libs.unpeek.livedata
    //通过标签直接生成shape，无需再写shape.xml
    api libs.backgroundlibrary.library
}