plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.ksp)
}

android {
    namespace 'com.mvvmhelper.demo'

    compileSdkVersion  36
    defaultConfig {
        applicationId "com.mvvmhelper.demo"
        minSdk  23
        targetSdk  36
        versionCode 17
        versionName "1.1.7"
        multiDexEnabled true

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
        }
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    buildTypes {
        debug {
            minifyEnabled false //关闭混淆
            shrinkResources false
            zipAlignEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true //开启混淆
            shrinkResources true
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    kotlin {
        jvmToolchain(17) // 自动设置 Java 17 兼容性
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.multidex)

    //banner
    implementation libs.banner
    //微信本地数据存储方案，替代SP
    implementation libs.mmkv
    //lottie动画
    implementation libs.lottie
    implementation libs.baserecyclerviewadapterhelper

    //rxhttp
    implementation libs.okhttp
    ksp libs.rxhttp.compiler
    implementation project(path: ':helper')
//    implementation 'com.github.hegaojian:MvvmHelper:1.2.1'


}
